services:
  db:
    image: postgres:15
    container_name: optimeal_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=optimeal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - TZ=Asia/Seoul  # [추가] 한국 시간대 설정
    volumes:
      - ./pg_data:/var/lib/postgresql/data  # [핵심 변경] 프로젝트 폴더 내 pg_data에 저장
    restart: always